/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as ProductsProductIdIndexRouteImport } from './routes/products/$productId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdIndexRoute = ProductsProductIdIndexRouteImport.update({
  id: '/products/$productId/',
  path: '/products/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community': typeof CommunityIndexRoute
  '/contact': typeof ContactIndexRoute
  '/products': typeof ProductsIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community': typeof CommunityIndexRoute
  '/contact': typeof ContactIndexRoute
  '/products': typeof ProductsIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/products/$productId': typeof ProductsProductIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community/': typeof CommunityIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/products/$productId/': typeof ProductsProductIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/contact'
    | '/products'
    | '/vendors'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/community'
    | '/contact'
    | '/products'
    | '/vendors'
    | '/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/community/'
    | '/contact/'
    | '/products/'
    | '/vendors/'
    | '/products/$productId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  ProductsProductIdIndexRoute: typeof ProductsProductIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId/': {
      id: '/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  ProductsProductIdIndexRoute: ProductsProductIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
