/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as vendorRouteRouteImport } from './routes/(vendor)/route'
import { Route as userRouteRouteImport } from './routes/(user)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as legalRouteRouteImport } from './routes/(legal)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as publicVendorsIndexRouteImport } from './routes/(public)/vendors/index'
import { Route as publicProductsIndexRouteImport } from './routes/(public)/products/index'
import { Route as publicContactIndexRouteImport } from './routes/(public)/contact/index'
import { Route as publicCommunityIndexRouteImport } from './routes/(public)/community/index'
import { Route as legalTermsOfUseIndexRouteImport } from './routes/(legal)/terms-of-use/index'
import { Route as legalTermsOfSalesIndexRouteImport } from './routes/(legal)/terms-of-sales/index'
import { Route as legalReturnsPolicyIndexRouteImport } from './routes/(legal)/returns-policy/index'
import { Route as legalPrivacyPolicyIndexRouteImport } from './routes/(legal)/privacy-policy/index'
import { Route as legalCookiesPolicyIndexRouteImport } from './routes/(legal)/cookies-policy/index'
import { Route as authSignUpSplatRouteImport } from './routes/(auth)/sign-up/$'
import { Route as authSignInSplatRouteImport } from './routes/(auth)/sign-in/$'
import { Route as vendorVendorUsersIndexRouteImport } from './routes/(vendor)/vendor.users/index'
import { Route as vendorVendorRequestsIndexRouteImport } from './routes/(vendor)/vendor.requests/index'
import { Route as vendorVendorProductsIndexRouteImport } from './routes/(vendor)/vendor.products/index'
import { Route as vendorVendorOrdersIndexRouteImport } from './routes/(vendor)/vendor.orders/index'
import { Route as vendorVendorDashboardIndexRouteImport } from './routes/(vendor)/vendor.dashboard/index'
import { Route as userUserRequestsIndexRouteImport } from './routes/(user)/user.requests/index'
import { Route as userUserOrdersIndexRouteImport } from './routes/(user)/user.orders/index'
import { Route as userUserCheckoutIndexRouteImport } from './routes/(user)/user.checkout/index'
import { Route as publicProductsProductIdIndexRouteImport } from './routes/(public)/products/$productId/index'
import { Route as adminAdminVendorsIndexRouteImport } from './routes/(admin)/admin.vendors/index'
import { Route as adminAdminUsersIndexRouteImport } from './routes/(admin)/admin.users/index'
import { Route as adminAdminProductsIndexRouteImport } from './routes/(admin)/admin.products/index'
import { Route as adminAdminOrdersIndexRouteImport } from './routes/(admin)/admin.orders/index'
import { Route as adminAdminDashboardIndexRouteImport } from './routes/(admin)/admin.dashboard/index'
import { Route as adminAdminCategoriesIndexRouteImport } from './routes/(admin)/admin.categories/index'
import { Route as apiApiOzowNotifyRouteImport } from './routes/(api)/api.ozow/notify'
import { Route as userUserOrdersOrderIdIndexRouteImport } from './routes/(user)/user.orders/$orderId/index'
import { Route as userUserOrdersOrderIdDeliveryIndexRouteImport } from './routes/(user)/user.orders/$orderId/delivery/index'

const vendorRouteRoute = vendorRouteRouteImport.update({
  id: '/(vendor)',
  getParentRoute: () => rootRouteImport,
} as any)
const userRouteRoute = userRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const legalRouteRoute = legalRouteRouteImport.update({
  id: '/(legal)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicVendorsIndexRoute = publicVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicProductsIndexRoute = publicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicContactIndexRoute = publicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCommunityIndexRoute = publicCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => publicRouteRoute,
} as any)
const legalTermsOfUseIndexRoute = legalTermsOfUseIndexRouteImport.update({
  id: '/terms-of-use/',
  path: '/terms-of-use/',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalTermsOfSalesIndexRoute = legalTermsOfSalesIndexRouteImport.update({
  id: '/terms-of-sales/',
  path: '/terms-of-sales/',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalReturnsPolicyIndexRoute = legalReturnsPolicyIndexRouteImport.update({
  id: '/returns-policy/',
  path: '/returns-policy/',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalPrivacyPolicyIndexRoute = legalPrivacyPolicyIndexRouteImport.update({
  id: '/privacy-policy/',
  path: '/privacy-policy/',
  getParentRoute: () => legalRouteRoute,
} as any)
const legalCookiesPolicyIndexRoute = legalCookiesPolicyIndexRouteImport.update({
  id: '/cookies-policy/',
  path: '/cookies-policy/',
  getParentRoute: () => legalRouteRoute,
} as any)
const authSignUpSplatRoute = authSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInSplatRoute = authSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => authRouteRoute,
} as any)
const vendorVendorUsersIndexRoute = vendorVendorUsersIndexRouteImport.update({
  id: '/vendor/users/',
  path: '/vendor/users/',
  getParentRoute: () => vendorRouteRoute,
} as any)
const vendorVendorRequestsIndexRoute =
  vendorVendorRequestsIndexRouteImport.update({
    id: '/vendor/requests/',
    path: '/vendor/requests/',
    getParentRoute: () => vendorRouteRoute,
  } as any)
const vendorVendorProductsIndexRoute =
  vendorVendorProductsIndexRouteImport.update({
    id: '/vendor/products/',
    path: '/vendor/products/',
    getParentRoute: () => vendorRouteRoute,
  } as any)
const vendorVendorOrdersIndexRoute = vendorVendorOrdersIndexRouteImport.update({
  id: '/vendor/orders/',
  path: '/vendor/orders/',
  getParentRoute: () => vendorRouteRoute,
} as any)
const vendorVendorDashboardIndexRoute =
  vendorVendorDashboardIndexRouteImport.update({
    id: '/vendor/dashboard/',
    path: '/vendor/dashboard/',
    getParentRoute: () => vendorRouteRoute,
  } as any)
const userUserRequestsIndexRoute = userUserRequestsIndexRouteImport.update({
  id: '/user/requests/',
  path: '/user/requests/',
  getParentRoute: () => userRouteRoute,
} as any)
const userUserOrdersIndexRoute = userUserOrdersIndexRouteImport.update({
  id: '/user/orders/',
  path: '/user/orders/',
  getParentRoute: () => userRouteRoute,
} as any)
const userUserCheckoutIndexRoute = userUserCheckoutIndexRouteImport.update({
  id: '/user/checkout/',
  path: '/user/checkout/',
  getParentRoute: () => userRouteRoute,
} as any)
const publicProductsProductIdIndexRoute =
  publicProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const adminAdminVendorsIndexRoute = adminAdminVendorsIndexRouteImport.update({
  id: '/admin/vendors/',
  path: '/admin/vendors/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminUsersIndexRoute = adminAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminProductsIndexRoute = adminAdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminOrdersIndexRoute = adminAdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminDashboardIndexRoute =
  adminAdminDashboardIndexRouteImport.update({
    id: '/admin/dashboard/',
    path: '/admin/dashboard/',
    getParentRoute: () => adminRouteRoute,
  } as any)
const adminAdminCategoriesIndexRoute =
  adminAdminCategoriesIndexRouteImport.update({
    id: '/admin/categories/',
    path: '/admin/categories/',
    getParentRoute: () => adminRouteRoute,
  } as any)
const apiApiOzowNotifyRoute = apiApiOzowNotifyRouteImport.update({
  id: '/(api)/api/ozow/notify',
  path: '/api/ozow/notify',
  getParentRoute: () => rootRouteImport,
} as any)
const userUserOrdersOrderIdIndexRoute =
  userUserOrdersOrderIdIndexRouteImport.update({
    id: '/user/orders/$orderId/',
    path: '/user/orders/$orderId/',
    getParentRoute: () => userRouteRoute,
  } as any)
const userUserOrdersOrderIdDeliveryIndexRoute =
  userUserOrdersOrderIdDeliveryIndexRouteImport.update({
    id: '/user/orders/$orderId/delivery/',
    path: '/user/orders/$orderId/delivery/',
    getParentRoute: () => userRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/sign-in/$': typeof authSignInSplatRoute
  '/sign-up/$': typeof authSignUpSplatRoute
  '/cookies-policy': typeof legalCookiesPolicyIndexRoute
  '/privacy-policy': typeof legalPrivacyPolicyIndexRoute
  '/returns-policy': typeof legalReturnsPolicyIndexRoute
  '/terms-of-sales': typeof legalTermsOfSalesIndexRoute
  '/terms-of-use': typeof legalTermsOfUseIndexRoute
  '/community': typeof publicCommunityIndexRoute
  '/contact': typeof publicContactIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/vendors': typeof publicVendorsIndexRoute
  '/api/ozow/notify': typeof apiApiOzowNotifyRoute
  '/admin/categories': typeof adminAdminCategoriesIndexRoute
  '/admin/dashboard': typeof adminAdminDashboardIndexRoute
  '/admin/orders': typeof adminAdminOrdersIndexRoute
  '/admin/products': typeof adminAdminProductsIndexRoute
  '/admin/users': typeof adminAdminUsersIndexRoute
  '/admin/vendors': typeof adminAdminVendorsIndexRoute
  '/products/$productId': typeof publicProductsProductIdIndexRoute
  '/user/checkout': typeof userUserCheckoutIndexRoute
  '/user/orders': typeof userUserOrdersIndexRoute
  '/user/requests': typeof userUserRequestsIndexRoute
  '/vendor/dashboard': typeof vendorVendorDashboardIndexRoute
  '/vendor/orders': typeof vendorVendorOrdersIndexRoute
  '/vendor/products': typeof vendorVendorProductsIndexRoute
  '/vendor/requests': typeof vendorVendorRequestsIndexRoute
  '/vendor/users': typeof vendorVendorUsersIndexRoute
  '/user/orders/$orderId': typeof userUserOrdersOrderIdIndexRoute
  '/user/orders/$orderId/delivery': typeof userUserOrdersOrderIdDeliveryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/sign-in/$': typeof authSignInSplatRoute
  '/sign-up/$': typeof authSignUpSplatRoute
  '/cookies-policy': typeof legalCookiesPolicyIndexRoute
  '/privacy-policy': typeof legalPrivacyPolicyIndexRoute
  '/returns-policy': typeof legalReturnsPolicyIndexRoute
  '/terms-of-sales': typeof legalTermsOfSalesIndexRoute
  '/terms-of-use': typeof legalTermsOfUseIndexRoute
  '/community': typeof publicCommunityIndexRoute
  '/contact': typeof publicContactIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/vendors': typeof publicVendorsIndexRoute
  '/api/ozow/notify': typeof apiApiOzowNotifyRoute
  '/admin/categories': typeof adminAdminCategoriesIndexRoute
  '/admin/dashboard': typeof adminAdminDashboardIndexRoute
  '/admin/orders': typeof adminAdminOrdersIndexRoute
  '/admin/products': typeof adminAdminProductsIndexRoute
  '/admin/users': typeof adminAdminUsersIndexRoute
  '/admin/vendors': typeof adminAdminVendorsIndexRoute
  '/products/$productId': typeof publicProductsProductIdIndexRoute
  '/user/checkout': typeof userUserCheckoutIndexRoute
  '/user/orders': typeof userUserOrdersIndexRoute
  '/user/requests': typeof userUserRequestsIndexRoute
  '/vendor/dashboard': typeof vendorVendorDashboardIndexRoute
  '/vendor/orders': typeof vendorVendorOrdersIndexRoute
  '/vendor/products': typeof vendorVendorProductsIndexRoute
  '/vendor/requests': typeof vendorVendorRequestsIndexRoute
  '/vendor/users': typeof vendorVendorUsersIndexRoute
  '/user/orders/$orderId': typeof userUserOrdersOrderIdIndexRoute
  '/user/orders/$orderId/delivery': typeof userUserOrdersOrderIdDeliveryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(legal)': typeof legalRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/(vendor)': typeof vendorRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/sign-in/$': typeof authSignInSplatRoute
  '/(auth)/sign-up/$': typeof authSignUpSplatRoute
  '/(legal)/cookies-policy/': typeof legalCookiesPolicyIndexRoute
  '/(legal)/privacy-policy/': typeof legalPrivacyPolicyIndexRoute
  '/(legal)/returns-policy/': typeof legalReturnsPolicyIndexRoute
  '/(legal)/terms-of-sales/': typeof legalTermsOfSalesIndexRoute
  '/(legal)/terms-of-use/': typeof legalTermsOfUseIndexRoute
  '/(public)/community/': typeof publicCommunityIndexRoute
  '/(public)/contact/': typeof publicContactIndexRoute
  '/(public)/products/': typeof publicProductsIndexRoute
  '/(public)/vendors/': typeof publicVendorsIndexRoute
  '/(api)/api/ozow/notify': typeof apiApiOzowNotifyRoute
  '/(admin)/admin/categories/': typeof adminAdminCategoriesIndexRoute
  '/(admin)/admin/dashboard/': typeof adminAdminDashboardIndexRoute
  '/(admin)/admin/orders/': typeof adminAdminOrdersIndexRoute
  '/(admin)/admin/products/': typeof adminAdminProductsIndexRoute
  '/(admin)/admin/users/': typeof adminAdminUsersIndexRoute
  '/(admin)/admin/vendors/': typeof adminAdminVendorsIndexRoute
  '/(public)/products/$productId/': typeof publicProductsProductIdIndexRoute
  '/(user)/user/checkout/': typeof userUserCheckoutIndexRoute
  '/(user)/user/orders/': typeof userUserOrdersIndexRoute
  '/(user)/user/requests/': typeof userUserRequestsIndexRoute
  '/(vendor)/vendor/dashboard/': typeof vendorVendorDashboardIndexRoute
  '/(vendor)/vendor/orders/': typeof vendorVendorOrdersIndexRoute
  '/(vendor)/vendor/products/': typeof vendorVendorProductsIndexRoute
  '/(vendor)/vendor/requests/': typeof vendorVendorRequestsIndexRoute
  '/(vendor)/vendor/users/': typeof vendorVendorUsersIndexRoute
  '/(user)/user/orders/$orderId/': typeof userUserOrdersOrderIdIndexRoute
  '/(user)/user/orders/$orderId/delivery/': typeof userUserOrdersOrderIdDeliveryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/cookies-policy'
    | '/privacy-policy'
    | '/returns-policy'
    | '/terms-of-sales'
    | '/terms-of-use'
    | '/community'
    | '/contact'
    | '/products'
    | '/vendors'
    | '/api/ozow/notify'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/admin/vendors'
    | '/products/$productId'
    | '/user/checkout'
    | '/user/orders'
    | '/user/requests'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/requests'
    | '/vendor/users'
    | '/user/orders/$orderId'
    | '/user/orders/$orderId/delivery'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/cookies-policy'
    | '/privacy-policy'
    | '/returns-policy'
    | '/terms-of-sales'
    | '/terms-of-use'
    | '/community'
    | '/contact'
    | '/products'
    | '/vendors'
    | '/api/ozow/notify'
    | '/admin/categories'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/admin/vendors'
    | '/products/$productId'
    | '/user/checkout'
    | '/user/orders'
    | '/user/requests'
    | '/vendor/dashboard'
    | '/vendor/orders'
    | '/vendor/products'
    | '/vendor/requests'
    | '/vendor/users'
    | '/user/orders/$orderId'
    | '/user/orders/$orderId/delivery'
  id:
    | '__root__'
    | '/(admin)'
    | '/(auth)'
    | '/(legal)'
    | '/(public)'
    | '/(user)'
    | '/(vendor)'
    | '/(public)/'
    | '/(auth)/sign-in/$'
    | '/(auth)/sign-up/$'
    | '/(legal)/cookies-policy/'
    | '/(legal)/privacy-policy/'
    | '/(legal)/returns-policy/'
    | '/(legal)/terms-of-sales/'
    | '/(legal)/terms-of-use/'
    | '/(public)/community/'
    | '/(public)/contact/'
    | '/(public)/products/'
    | '/(public)/vendors/'
    | '/(api)/api/ozow/notify'
    | '/(admin)/admin/categories/'
    | '/(admin)/admin/dashboard/'
    | '/(admin)/admin/orders/'
    | '/(admin)/admin/products/'
    | '/(admin)/admin/users/'
    | '/(admin)/admin/vendors/'
    | '/(public)/products/$productId/'
    | '/(user)/user/checkout/'
    | '/(user)/user/orders/'
    | '/(user)/user/requests/'
    | '/(vendor)/vendor/dashboard/'
    | '/(vendor)/vendor/orders/'
    | '/(vendor)/vendor/products/'
    | '/(vendor)/vendor/requests/'
    | '/(vendor)/vendor/users/'
    | '/(user)/user/orders/$orderId/'
    | '/(user)/user/orders/$orderId/delivery/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  legalRouteRoute: typeof legalRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
  vendorRouteRoute: typeof vendorRouteRouteWithChildren
  apiApiOzowNotifyRoute: typeof apiApiOzowNotifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(vendor)': {
      id: '/(vendor)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof vendorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)': {
      id: '/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof userRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)': {
      id: '/(legal)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof legalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/vendors/': {
      id: '/(public)/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof publicVendorsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/products/': {
      id: '/(public)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof publicProductsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/contact/': {
      id: '/(public)/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicContactIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/community/': {
      id: '/(public)/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof publicCommunityIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(legal)/terms-of-use/': {
      id: '/(legal)/terms-of-use/'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof legalTermsOfUseIndexRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/terms-of-sales/': {
      id: '/(legal)/terms-of-sales/'
      path: '/terms-of-sales'
      fullPath: '/terms-of-sales'
      preLoaderRoute: typeof legalTermsOfSalesIndexRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/returns-policy/': {
      id: '/(legal)/returns-policy/'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof legalReturnsPolicyIndexRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/privacy-policy/': {
      id: '/(legal)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof legalPrivacyPolicyIndexRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(legal)/cookies-policy/': {
      id: '/(legal)/cookies-policy/'
      path: '/cookies-policy'
      fullPath: '/cookies-policy'
      preLoaderRoute: typeof legalCookiesPolicyIndexRouteImport
      parentRoute: typeof legalRouteRoute
    }
    '/(auth)/sign-up/$': {
      id: '/(auth)/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof authSignUpSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/$': {
      id: '/(auth)/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof authSignInSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(vendor)/vendor/users/': {
      id: '/(vendor)/vendor/users/'
      path: '/vendor/users'
      fullPath: '/vendor/users'
      preLoaderRoute: typeof vendorVendorUsersIndexRouteImport
      parentRoute: typeof vendorRouteRoute
    }
    '/(vendor)/vendor/requests/': {
      id: '/(vendor)/vendor/requests/'
      path: '/vendor/requests'
      fullPath: '/vendor/requests'
      preLoaderRoute: typeof vendorVendorRequestsIndexRouteImport
      parentRoute: typeof vendorRouteRoute
    }
    '/(vendor)/vendor/products/': {
      id: '/(vendor)/vendor/products/'
      path: '/vendor/products'
      fullPath: '/vendor/products'
      preLoaderRoute: typeof vendorVendorProductsIndexRouteImport
      parentRoute: typeof vendorRouteRoute
    }
    '/(vendor)/vendor/orders/': {
      id: '/(vendor)/vendor/orders/'
      path: '/vendor/orders'
      fullPath: '/vendor/orders'
      preLoaderRoute: typeof vendorVendorOrdersIndexRouteImport
      parentRoute: typeof vendorRouteRoute
    }
    '/(vendor)/vendor/dashboard/': {
      id: '/(vendor)/vendor/dashboard/'
      path: '/vendor/dashboard'
      fullPath: '/vendor/dashboard'
      preLoaderRoute: typeof vendorVendorDashboardIndexRouteImport
      parentRoute: typeof vendorRouteRoute
    }
    '/(user)/user/requests/': {
      id: '/(user)/user/requests/'
      path: '/user/requests'
      fullPath: '/user/requests'
      preLoaderRoute: typeof userUserRequestsIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/user/orders/': {
      id: '/(user)/user/orders/'
      path: '/user/orders'
      fullPath: '/user/orders'
      preLoaderRoute: typeof userUserOrdersIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/user/checkout/': {
      id: '/(user)/user/checkout/'
      path: '/user/checkout'
      fullPath: '/user/checkout'
      preLoaderRoute: typeof userUserCheckoutIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(public)/products/$productId/': {
      id: '/(public)/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof publicProductsProductIdIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(admin)/admin/vendors/': {
      id: '/(admin)/admin/vendors/'
      path: '/admin/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof adminAdminVendorsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/users/': {
      id: '/(admin)/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminAdminUsersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/products/': {
      id: '/(admin)/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof adminAdminProductsIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/orders/': {
      id: '/(admin)/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof adminAdminOrdersIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/dashboard/': {
      id: '/(admin)/admin/dashboard/'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof adminAdminDashboardIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/categories/': {
      id: '/(admin)/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof adminAdminCategoriesIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(api)/api/ozow/notify': {
      id: '/(api)/api/ozow/notify'
      path: '/api/ozow/notify'
      fullPath: '/api/ozow/notify'
      preLoaderRoute: typeof apiApiOzowNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)/user/orders/$orderId/': {
      id: '/(user)/user/orders/$orderId/'
      path: '/user/orders/$orderId'
      fullPath: '/user/orders/$orderId'
      preLoaderRoute: typeof userUserOrdersOrderIdIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/user/orders/$orderId/delivery/': {
      id: '/(user)/user/orders/$orderId/delivery/'
      path: '/user/orders/$orderId/delivery'
      fullPath: '/user/orders/$orderId/delivery'
      preLoaderRoute: typeof userUserOrdersOrderIdDeliveryIndexRouteImport
      parentRoute: typeof userRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminAdminCategoriesIndexRoute: typeof adminAdminCategoriesIndexRoute
  adminAdminDashboardIndexRoute: typeof adminAdminDashboardIndexRoute
  adminAdminOrdersIndexRoute: typeof adminAdminOrdersIndexRoute
  adminAdminProductsIndexRoute: typeof adminAdminProductsIndexRoute
  adminAdminUsersIndexRoute: typeof adminAdminUsersIndexRoute
  adminAdminVendorsIndexRoute: typeof adminAdminVendorsIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminCategoriesIndexRoute: adminAdminCategoriesIndexRoute,
  adminAdminDashboardIndexRoute: adminAdminDashboardIndexRoute,
  adminAdminOrdersIndexRoute: adminAdminOrdersIndexRoute,
  adminAdminProductsIndexRoute: adminAdminProductsIndexRoute,
  adminAdminUsersIndexRoute: adminAdminUsersIndexRoute,
  adminAdminVendorsIndexRoute: adminAdminVendorsIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface authRouteRouteChildren {
  authSignInSplatRoute: typeof authSignInSplatRoute
  authSignUpSplatRoute: typeof authSignUpSplatRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInSplatRoute: authSignInSplatRoute,
  authSignUpSplatRoute: authSignUpSplatRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface legalRouteRouteChildren {
  legalCookiesPolicyIndexRoute: typeof legalCookiesPolicyIndexRoute
  legalPrivacyPolicyIndexRoute: typeof legalPrivacyPolicyIndexRoute
  legalReturnsPolicyIndexRoute: typeof legalReturnsPolicyIndexRoute
  legalTermsOfSalesIndexRoute: typeof legalTermsOfSalesIndexRoute
  legalTermsOfUseIndexRoute: typeof legalTermsOfUseIndexRoute
}

const legalRouteRouteChildren: legalRouteRouteChildren = {
  legalCookiesPolicyIndexRoute: legalCookiesPolicyIndexRoute,
  legalPrivacyPolicyIndexRoute: legalPrivacyPolicyIndexRoute,
  legalReturnsPolicyIndexRoute: legalReturnsPolicyIndexRoute,
  legalTermsOfSalesIndexRoute: legalTermsOfSalesIndexRoute,
  legalTermsOfUseIndexRoute: legalTermsOfUseIndexRoute,
}

const legalRouteRouteWithChildren = legalRouteRoute._addFileChildren(
  legalRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicCommunityIndexRoute: typeof publicCommunityIndexRoute
  publicContactIndexRoute: typeof publicContactIndexRoute
  publicProductsIndexRoute: typeof publicProductsIndexRoute
  publicVendorsIndexRoute: typeof publicVendorsIndexRoute
  publicProductsProductIdIndexRoute: typeof publicProductsProductIdIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicCommunityIndexRoute: publicCommunityIndexRoute,
  publicContactIndexRoute: publicContactIndexRoute,
  publicProductsIndexRoute: publicProductsIndexRoute,
  publicVendorsIndexRoute: publicVendorsIndexRoute,
  publicProductsProductIdIndexRoute: publicProductsProductIdIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface userRouteRouteChildren {
  userUserCheckoutIndexRoute: typeof userUserCheckoutIndexRoute
  userUserOrdersIndexRoute: typeof userUserOrdersIndexRoute
  userUserRequestsIndexRoute: typeof userUserRequestsIndexRoute
  userUserOrdersOrderIdIndexRoute: typeof userUserOrdersOrderIdIndexRoute
  userUserOrdersOrderIdDeliveryIndexRoute: typeof userUserOrdersOrderIdDeliveryIndexRoute
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userUserCheckoutIndexRoute: userUserCheckoutIndexRoute,
  userUserOrdersIndexRoute: userUserOrdersIndexRoute,
  userUserRequestsIndexRoute: userUserRequestsIndexRoute,
  userUserOrdersOrderIdIndexRoute: userUserOrdersOrderIdIndexRoute,
  userUserOrdersOrderIdDeliveryIndexRoute:
    userUserOrdersOrderIdDeliveryIndexRoute,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

interface vendorRouteRouteChildren {
  vendorVendorDashboardIndexRoute: typeof vendorVendorDashboardIndexRoute
  vendorVendorOrdersIndexRoute: typeof vendorVendorOrdersIndexRoute
  vendorVendorProductsIndexRoute: typeof vendorVendorProductsIndexRoute
  vendorVendorRequestsIndexRoute: typeof vendorVendorRequestsIndexRoute
  vendorVendorUsersIndexRoute: typeof vendorVendorUsersIndexRoute
}

const vendorRouteRouteChildren: vendorRouteRouteChildren = {
  vendorVendorDashboardIndexRoute: vendorVendorDashboardIndexRoute,
  vendorVendorOrdersIndexRoute: vendorVendorOrdersIndexRoute,
  vendorVendorProductsIndexRoute: vendorVendorProductsIndexRoute,
  vendorVendorRequestsIndexRoute: vendorVendorRequestsIndexRoute,
  vendorVendorUsersIndexRoute: vendorVendorUsersIndexRoute,
}

const vendorRouteRouteWithChildren = vendorRouteRoute._addFileChildren(
  vendorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  legalRouteRoute: legalRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
  vendorRouteRoute: vendorRouteRouteWithChildren,
  apiApiOzowNotifyRoute: apiApiOzowNotifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
