/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as userRequestsIndexRouteImport } from './routes/(user)/requests/index'
import { Route as userOrdersIndexRouteImport } from './routes/(user)/orders/index'
import { Route as userCheckoutIndexRouteImport } from './routes/(user)/checkout/index'
import { Route as publicVendorsIndexRouteImport } from './routes/(public)/vendors/index'
import { Route as publicProductsIndexRouteImport } from './routes/(public)/products/index'
import { Route as publicContactIndexRouteImport } from './routes/(public)/contact/index'
import { Route as publicCommunityIndexRouteImport } from './routes/(public)/community/index'
import { Route as authSignUpSplatRouteImport } from './routes/(auth)/sign-up/$'
import { Route as authSignInSplatRouteImport } from './routes/(auth)/sign-in/$'
import { Route as publicVendorsVendorIdIndexRouteImport } from './routes/(public)/vendors/$vendorId/index'
import { Route as publicProductsProductIdIndexRouteImport } from './routes/(public)/products/$productId/index'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const userRequestsIndexRoute = userRequestsIndexRouteImport.update({
  id: '/(user)/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const userOrdersIndexRoute = userOrdersIndexRouteImport.update({
  id: '/(user)/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const userCheckoutIndexRoute = userCheckoutIndexRouteImport.update({
  id: '/(user)/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const publicVendorsIndexRoute = publicVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicProductsIndexRoute = publicProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicContactIndexRoute = publicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => publicRouteRoute,
} as any)
const publicCommunityIndexRoute = publicCommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => publicRouteRoute,
} as any)
const authSignUpSplatRoute = authSignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInSplatRoute = authSignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => authRouteRoute,
} as any)
const publicVendorsVendorIdIndexRoute =
  publicVendorsVendorIdIndexRouteImport.update({
    id: '/vendors/$vendorId/',
    path: '/vendors/$vendorId/',
    getParentRoute: () => publicRouteRoute,
  } as any)
const publicProductsProductIdIndexRoute =
  publicProductsProductIdIndexRouteImport.update({
    id: '/products/$productId/',
    path: '/products/$productId/',
    getParentRoute: () => publicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/sign-in/$': typeof authSignInSplatRoute
  '/sign-up/$': typeof authSignUpSplatRoute
  '/community': typeof publicCommunityIndexRoute
  '/contact': typeof publicContactIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/vendors': typeof publicVendorsIndexRoute
  '/checkout': typeof userCheckoutIndexRoute
  '/orders': typeof userOrdersIndexRoute
  '/requests': typeof userRequestsIndexRoute
  '/products/$productId': typeof publicProductsProductIdIndexRoute
  '/vendors/$vendorId': typeof publicVendorsVendorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/sign-in/$': typeof authSignInSplatRoute
  '/sign-up/$': typeof authSignUpSplatRoute
  '/community': typeof publicCommunityIndexRoute
  '/contact': typeof publicContactIndexRoute
  '/products': typeof publicProductsIndexRoute
  '/vendors': typeof publicVendorsIndexRoute
  '/checkout': typeof userCheckoutIndexRoute
  '/orders': typeof userOrdersIndexRoute
  '/requests': typeof userRequestsIndexRoute
  '/products/$productId': typeof publicProductsProductIdIndexRoute
  '/vendors/$vendorId': typeof publicVendorsVendorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(auth)/sign-in/$': typeof authSignInSplatRoute
  '/(auth)/sign-up/$': typeof authSignUpSplatRoute
  '/(public)/community/': typeof publicCommunityIndexRoute
  '/(public)/contact/': typeof publicContactIndexRoute
  '/(public)/products/': typeof publicProductsIndexRoute
  '/(public)/vendors/': typeof publicVendorsIndexRoute
  '/(user)/checkout/': typeof userCheckoutIndexRoute
  '/(user)/orders/': typeof userOrdersIndexRoute
  '/(user)/requests/': typeof userRequestsIndexRoute
  '/(public)/products/$productId/': typeof publicProductsProductIdIndexRoute
  '/(public)/vendors/$vendorId/': typeof publicVendorsVendorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/community'
    | '/contact'
    | '/products'
    | '/vendors'
    | '/checkout'
    | '/orders'
    | '/requests'
    | '/products/$productId'
    | '/vendors/$vendorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/community'
    | '/contact'
    | '/products'
    | '/vendors'
    | '/checkout'
    | '/orders'
    | '/requests'
    | '/products/$productId'
    | '/vendors/$vendorId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(public)'
    | '/(public)/'
    | '/(auth)/sign-in/$'
    | '/(auth)/sign-up/$'
    | '/(public)/community/'
    | '/(public)/contact/'
    | '/(public)/products/'
    | '/(public)/vendors/'
    | '/(user)/checkout/'
    | '/(user)/orders/'
    | '/(user)/requests/'
    | '/(public)/products/$productId/'
    | '/(public)/vendors/$vendorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  userCheckoutIndexRoute: typeof userCheckoutIndexRoute
  userOrdersIndexRoute: typeof userOrdersIndexRoute
  userRequestsIndexRoute: typeof userRequestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(user)/requests/': {
      id: '/(user)/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof userRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)/orders/': {
      id: '/(user)/orders/'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof userOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)/checkout/': {
      id: '/(user)/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof userCheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/vendors/': {
      id: '/(public)/vendors/'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof publicVendorsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/products/': {
      id: '/(public)/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof publicProductsIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/contact/': {
      id: '/(public)/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof publicContactIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/community/': {
      id: '/(public)/community/'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof publicCommunityIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(auth)/sign-up/$': {
      id: '/(auth)/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof authSignUpSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/$': {
      id: '/(auth)/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof authSignInSplatRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(public)/vendors/$vendorId/': {
      id: '/(public)/vendors/$vendorId/'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof publicVendorsVendorIdIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(public)/products/$productId/': {
      id: '/(public)/products/$productId/'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof publicProductsProductIdIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInSplatRoute: typeof authSignInSplatRoute
  authSignUpSplatRoute: typeof authSignUpSplatRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInSplatRoute: authSignInSplatRoute,
  authSignUpSplatRoute: authSignUpSplatRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
  publicCommunityIndexRoute: typeof publicCommunityIndexRoute
  publicContactIndexRoute: typeof publicContactIndexRoute
  publicProductsIndexRoute: typeof publicProductsIndexRoute
  publicVendorsIndexRoute: typeof publicVendorsIndexRoute
  publicProductsProductIdIndexRoute: typeof publicProductsProductIdIndexRoute
  publicVendorsVendorIdIndexRoute: typeof publicVendorsVendorIdIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
  publicCommunityIndexRoute: publicCommunityIndexRoute,
  publicContactIndexRoute: publicContactIndexRoute,
  publicProductsIndexRoute: publicProductsIndexRoute,
  publicVendorsIndexRoute: publicVendorsIndexRoute,
  publicProductsProductIdIndexRoute: publicProductsProductIdIndexRoute,
  publicVendorsVendorIdIndexRoute: publicVendorsVendorIdIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  userCheckoutIndexRoute: userCheckoutIndexRoute,
  userOrdersIndexRoute: userOrdersIndexRoute,
  userRequestsIndexRoute: userRequestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
